# Generated by Django 5.2.7 on 2025-11-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_age_alter_user_correction_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='libre_registered',
            field=models.BooleanField(default=False),
        ),
    ]
