# Generated by Django 5.2.7 on 2025-10-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_nutritionalinfo_alert_glucoserecord_insightreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libreconnection',
            name='password_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
