# Generated by Django 5.2.7 on 2025-10-29 09:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_libre_oauth_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentry',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='lunch', max_length=16),
        ),
        migrations.AlterField(
            model_name='glucoserecord',
            name='source',
            field=models.CharField(choices=[('manaual', 'Manual'), ('libre', 'Libre'), ('other', 'Other')], default='manual', max_length=50),
        ),
        migrations.AddIndex(
            model_name='glucoserecord',
            index=models.Index(fields=['user', 'timestamp'], name='core_glucos_user_id_6adc84_idx'),
        ),
        migrations.AddConstraint(
            model_name='glucoserecord',
            constraint=models.UniqueConstraint(fields=('user', 'timestamp', 'glucose_level', 'source'), name='uniq_glucose_row'),
        ),
    ]
