# Generated by Django 5.2.7 on 2025-10-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_foodentry_meal_type_alter_glucoserecord_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucoserecord',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('libre', 'Libre'), ('other', 'Other')], default='manual', max_length=50),
        ),
    ]
