# Generated by Django 5.2.7 on 2025-11-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_glucoserecord_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='glucoserecord',
            name='meal_timing',
            field=models.CharField(blank=True, choices=[('before_meal', 'Before Meal'), ('after_meal', 'After Meal'), ('fasting', 'Fasting'), ('bedtime', 'Bedtime'), ('random', 'Random')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='glucoserecord',
            name='mood',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='glucoserecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
