# Generated by Django 5.2.7 on 2025-11-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_glucoserecord_meal_timing_glucoserecord_mood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='total_calories',
            field=models.FloatField(blank=True, help_text='Total calories', null=True),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='total_carbs',
            field=models.FloatField(blank=True, help_text='Total carbohydrates in grams', null=True),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='total_fat',
            field=models.FloatField(blank=True, help_text='Total fat in grams', null=True),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='total_protein',
            field=models.FloatField(blank=True, help_text='Total protein in grams', null=True),
        ),
    ]
