# Generated by Django 5.2.7 on 2026-08-22 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_foodentry_total_calories_foodentry_total_carbs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsulinDose',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('units', models.FloatField()),
                ('recommended_units', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('meal', 'Meal Dose'), ('correction', 'Correction Only'), ('manual', 'Manual Entry')], default='meal', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('food_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insulin_doses', to='core.foodentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insulin_doses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'timestamp'], name='core_insuli_user_id_ac41f6_idx')],
            },
        ),
    ]
